[features]
seeds = false
[programs.devnet]
chainlink_solana_dapp = "Hdbm4AdtUr5juLEEr3pCzSSYDGo5UjML9DNVK2TmBd7wpro"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
